/**
 * Builds the downloadable Shopify Typography Kit bundles into `kits/`.
 *
 * Every line of install code is produced by the SAME generator
 * functions the website ships (lib/generators/*), composed through the
 * battle-tested `fromSimple` legacy path. Nothing here hand-writes
 * @font-face or CSS-variable output — correctness is inherited from
 * the generator's own unit test suite. That matters because the
 * product ships and then nobody watches it for ten months.
 *
 * Regenerable + deterministic: the script wipes `kits/` and rebuilds
 * from content/kits.ts + content/themes.ts. Run:
 *   npx tsx scripts/build-kits.ts
 *
 * Output per kit: a README, a printable specimen, font-download
 * instructions, a license/usage sheet, an uninstall sheet, and a
 * per-theme install folder (font-face.css, css-variables.css,
 * settings_schema.snippet.json, preload.liquid, INSTALL.txt) for all
 * 13 free Shopify OS 2.0 themes.
 */

import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildCssVariableOverrides,
  buildFontFaceCss,
  fromSimple,
  slugify,
  type SimpleGeneratorInput,
} from "../lib/generators";
import { KITS, type Kit, type KitFont } from "../content/kits";
import { THEMES } from "../content/themes";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const OUT = resolve(projectRoot, "kits");

/** One generator input per family. Regular(400) + Bold(700). */
function inputFor(
  font: KitFont,
  applyTo: ReadonlyArray<"heading" | "body">,
): SimpleGeneratorInput {
  const [primary, ...rest] = font.weights;
  return {
    fontName: font.family,
    formats: ["woff2"],
    weight: primary,
    style: "normal",
    fileBaseName: slugify(font.family),
    applyTo,
    additionalWeights: rest.length > 0 ? rest : undefined,
  };
}

/** The exact WOFF2 filenames the generated @font-face url()s expect. */
function expectedFiles(font: KitFont): string[] {
  const base = slugify(font.family);
  return font.weights.map((w) => `${base}-${w}.woff2`);
}

function fontFaceFor(kit: Kit): string {
  if (kit.singleFamily) {
    return buildFontFaceCss(
      fromSimple(inputFor(kit.heading, ["heading", "body"])),
    );
  }
  return [
    `/* Heading family: ${kit.heading.family} */`,
    buildFontFaceCss(fromSimple(inputFor(kit.heading, ["heading"]))),
    "",
    `/* Body family: ${kit.body.family} */`,
    buildFontFaceCss(fromSimple(inputFor(kit.body, ["body"]))),
  ].join("\n");
}

function cssVarsFor(kit: Kit): string {
  if (kit.singleFamily) {
    return buildCssVariableOverrides(
      fromSimple(inputFor(kit.heading, ["heading", "body"])),
    );
  }
  return [
    `/* Heading family → heading CSS variables */`,
    buildCssVariableOverrides(fromSimple(inputFor(kit.heading, ["heading"]))),
    "",
    `/* Body family → body CSS variables */`,
    buildCssVariableOverrides(fromSimple(inputFor(kit.body, ["body"]))),
  ].join("\n");
}

function allExpectedFiles(kit: Kit): string[] {
  if (kit.singleFamily) return expectedFiles(kit.heading);
  return [...expectedFiles(kit.heading), ...expectedFiles(kit.body)];
}

function w(path: string, body: string): void {
  const full = resolve(OUT, path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, body.replace(/\r\n/g, "\n"), "utf8");
}

function kitReadme(kit: Kit): string {
  const fonts = kit.singleFamily
    ? `${kit.heading.family} (used for both headings and body)`
    : `${kit.heading.family} (headings) + ${kit.body.family} (body)`;
  return `SHOPIFY TYPOGRAPHY KIT — ${kit.name}
${"=".repeat(48)}

For: ${kit.vertical}
Fonts: ${fonts}
File budget: ${kit.fileBudget}

WHY THIS PAIRING
${kit.rationale}

THE ONE MISTAKE TO AVOID
${kit.pitfall}

WHAT'S IN THIS KIT
- fonts/DOWNLOAD.txt ....... exactly which font files to get (free) and how
- SPECIMEN.html ........... open in any browser to see the pairing
- install/<theme>/ ........ two copy-paste blocks for all 13 free Shopify themes
- LICENSE-AND-USAGE.txt ... you're cleared for commercial Shopify use; details inside
- UNINSTALL.txt ........... clean reversal in case you change your mind

QUICK START (~5 minutes)
1. Open fonts/DOWNLOAD.txt and get the font files (free, from Google Fonts).
2. Find your Shopify theme in install/ (e.g. install/dawn/).
3. Open INSTALL.txt in that folder — two blocks to paste, that's it.
4. Open SPECIMEN.html any time to preview what you're installing.

No account, no dependencies, nothing phones home. The install is pure
CSS — your storefront ships zero extra JavaScript.

Generated by Shopifont — shopifont.app
`;
}

function downloadTxt(kit: Kit): string {
  const fams = kit.singleFamily ? [kit.heading] : [kit.heading, kit.body];
  const blocks = fams
    .map((f) => {
      const files = expectedFiles(f)
        .map(
          (name, i) =>
            `   - ${f.family} ${f.weights[i]} (${
              f.weights[i] === 700 ? "Bold" : "Regular"
            })  →  rename the WOFF2 to:  ${name}`,
        )
        .join("\n");
      return `${f.family}
   Download page: ${f.googleFontsUrl}
   You need these weights as .woff2:
${files}`;
    })
    .join("\n\n");

  return `FONT FILES — ${kit.name}
${"=".repeat(48)}

Every font in this kit is licensed under the SIL Open Font License
(OFL). You may self-host and use it on a commercial Shopify storefront
for free. We don't ship the font binaries (that's how OFL self-hosting
is meant to work) — you fetch them once from Google Fonts and rename
them to the exact filenames the install code expects.

HOW TO GET WOFF2 FROM GOOGLE FONTS
1. Open the download page below for each family.
2. Click "Get font", then "Download all" — you'll get .ttf files.
3. Convert each .ttf you need to .woff2. Free, no signup:
      https://cloudconvert.com/ttf-to-woff2
   (or any TTF→WOFF2 converter — the format is what makes the file
   small and fast; this step is not optional).
4. Rename each .woff2 to the EXACT filename listed below. The install
   code references these names — a typo here is the only thing that
   can break the install.
5. Upload all of them to your theme's  assets/  folder.

${blocks}

That's every file. Total on your storefront: ${kit.fileBudget}.

Generated by Shopifont — shopifont.app
`;
}

function licenseTxt(kit: Kit): string {
  const fams = kit.singleFamily
    ? kit.heading.family
    : `${kit.heading.family} and ${kit.body.family}`;
  return `LICENSE & COMMERCIAL USE — ${kit.name}
${"=".repeat(48)}

THE FONTS
${fams} ${
    kit.singleFamily ? "is" : "are"
  } licensed under the SIL Open Font
License, Version 1.1 (OFL-1.1). In plain English, for a Shopify store:

  - YES, you can use ${
    kit.singleFamily ? "it" : "them"
  } on a commercial storefront.
  - YES, you can self-host the files in your theme's assets/ folder.
  - YES, you can use ${
    kit.singleFamily ? "it" : "them"
  } in paid ads, packaging, and email.
  - NO separate license, seat count, or pageview tier to worry about.
  - The ONLY OFL rule that matters to you: don't sell the font files
    themselves as a standalone font product. Using them on your store
    (and in this kit) is exactly what the license is for.

Full OFL text: https://openfontlicense.org

THIS KIT
You bought the curation, the per-theme install code, the specimen,
and the playbook — not the fonts (those are free). You may use this
kit on any number of stores you own or operate. Please don't
redistribute or resell the kit itself.

NO-QUESTIONS REFUND
If this kit doesn't work for your store, reply to your Gumroad
receipt within 30 days for a full refund. No explanation needed.
(This exists so you never have to wait on support — there is no
support queue by design; the kit is built to be self-contained.)

Generated by Shopifont — shopifont.app
`;
}

function uninstallTxt(kit: Kit): string {
  return `UNINSTALL — ${kit.name}
${"=".repeat(48)}

Nothing in this install is permanent or stateful. To remove it
completely:

1. In your theme code editor, open the file where you pasted the
   @font-face + CSS-variable blocks (assets/base.css for every free
   Shopify theme). Delete both blocks. They are contiguous and the
   only thing the install added to that file.

2. Delete the .woff2 files you uploaded from the assets/ folder:
${allExpectedFiles(kit)
  .map((f) => `      ${f}`)
  .join("\n")}

3. Hard-refresh your storefront (Ctrl+Shift+R / Cmd+Shift+R). Your
   theme's original fonts are back. There is no other state to clean
   up — the install was two CSS blocks and some font files, nothing
   more.

Generated by Shopifont — shopifont.app
`;
}

function installTxt(
  kit: Kit,
  themeName: string,
  injectionPoint: string,
  selector: string,
): string {
  const cleanInjection = injectionPoint.replace(/`/g, "");
  return `INSTALL — ${kit.name} on Shopify ${themeName}
${"=".repeat(48)}

Step 0, then two copy-paste blocks. ~5 minutes. Nothing else.

STEP 0 — GET THE FONTS
Follow ../../fonts/DOWNLOAD.txt. You must have the renamed .woff2
files uploaded to your theme's assets/ folder before the code below
will resolve. This is the ONLY step that can go wrong — the filenames
must match exactly. Get this right and the rest cannot fail.

STEP 1 — Paste the @font-face block
Open ${cleanInjection} in your ${themeName} theme code editor.
Paste the entire contents of:  font-face.css

STEP 2 — Paste the CSS variable overrides
Directly below what you just pasted (same file), paste the entire
contents of:  css-variables.css
This retargets ${themeName}'s heading/body font variables directly. It
needs no Theme Editor setup and it survives theme updates. ${themeName}
renders headings via selectors like ${selector} — they pick up the new
variables automatically. Save.

VERIFY
Hard-refresh your storefront (Ctrl+Shift+R / Cmd+Shift+R). Headings
and body now render in the kit fonts. In DevTools → Network, filter
.woff2 — the files should load from your own domain (not a third
party). That's the whole install.

Changed your mind? See ../../UNINSTALL.txt.

Generated by Shopifont — shopifont.app
`;
}

function specimenHtml(kit: Kit): string {
  const heading = kit.heading.family;
  const body = kit.body.family;
  const families = kit.singleFamily
    ? [heading]
    : [heading, body];
  const gf = families
    .map(
      (f) =>
        `family=${f.replace(/ /g, "+")}:wght@400;700`,
    )
    .join("&");
  const esc = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(kit.name)} — Specimen — Shopifont</title>
<!--
  PREVIEW ONLY. This page pulls fonts from Google's CDN purely so you
  can see the pairing before you install. Your LIVE storefront uses
  the self-hosted .woff2 files from this kit (no third-party CDN, no
  layout shift) — see the install/ folder. Do not copy this <link>
  into your theme.
-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?${gf}&display=swap" rel="stylesheet">
<style>
  :root { --h: ${JSON.stringify(heading)}; --b: ${JSON.stringify(body)}; }
  * { box-sizing: border-box; }
  body { margin: 0; background: #fff; color: #111;
         font-family: var(--b), system-ui, sans-serif; }
  .wrap { max-width: 760px; margin: 0 auto; padding: 48px 24px; }
  .tag { font-size: 12px; letter-spacing: .08em; text-transform: uppercase;
         color: #666; }
  h1,h2,h3 { font-family: var(--h), Georgia, serif; margin: .2em 0; line-height: 1.1; }
  h1 { font-size: 56px; font-weight: 700; }
  h2 { font-size: 34px; font-weight: 700; }
  h3 { font-size: 22px; font-weight: 700; }
  p  { font-size: 17px; line-height: 1.65; max-width: 60ch; }
  .card { border: 1px solid #e5e5e5; border-radius: 10px; padding: 22px;
          margin-top: 28px; }
  .price { font-family: var(--h), Georgia, serif; font-weight: 700;
           font-size: 20px; }
  .rule { border: 0; border-top: 1px solid #e5e5e5; margin: 40px 0; }
  .muted { color: #666; font-size: 14px; }
  .btn { display:inline-block; margin-top:14px; padding:12px 20px;
         background:#111; color:#fff; border-radius:8px; font-size:15px;
         font-family: var(--b), system-ui, sans-serif; }
</style>
</head>
<body>
  <div class="wrap">
    <p class="tag">Shopify Typography Kit — Specimen</p>
    <h1>${esc(kit.name)}</h1>
    <p class="muted">${esc(kit.vertical)} · ${esc(
    kit.singleFamily
      ? `${heading} (headings + body)`
      : `${heading} headings · ${body} body`,
  )}</p>
    <hr class="rule">

    <h2>Your headlines will look like this</h2>
    <p>And your body copy will read like this — the size, weight, and
       rhythm a real product page actually uses. ${esc(
         kit.rationale,
       )}</p>

    <h3>A sub-heading at product-section scale</h3>
    <p>Shipping &amp; returns, ingredient lists, the long descriptions
       that decide whether someone buys. This is the text doing the
       quiet work, set in ${esc(body)}.</p>

    <div class="card">
      <p class="tag">Product card</p>
      <h3>The Signature Piece</h3>
      <p class="muted">A short product subtitle in the body face.</p>
      <p class="price">$148.00</p>
      <span class="btn">Add to cart</span>
    </div>

    <hr class="rule">
    <p class="muted">Heads-up: ${esc(kit.pitfall)}</p>
    <p class="muted">Install code for all 13 free Shopify themes is in
       the install/ folder. Fonts: see fonts/DOWNLOAD.txt. Generated by
       Shopifont — shopifont.app</p>
  </div>
</body>
</html>
`;
}

function topReadme(): string {
  const list = KITS.map(
    (k) => `  - ${k.name}/  —  ${k.vertical}`,
  ).join("\n");
  return `SHOPIFY TYPOGRAPHY KITS
${"=".repeat(48)}

Each folder is a complete, self-contained kit: a proven font pairing,
copy-paste install code for all 13 free Shopify OS 2.0 themes, a
visual specimen, font-download instructions, a license/usage sheet,
and an uninstall sheet.

KITS IN THIS BUNDLE
${list}

HOW TO USE ANY KIT
1. Open the kit folder for your store's vibe.
2. Read its README.txt (2 minutes).
3. Get the fonts (fonts/DOWNLOAD.txt — free, from Google Fonts).
4. Find your theme under install/, follow INSTALL.txt.

LICENSE IN ONE LINE
Every font is SIL Open Font License — free for commercial Shopify
use, self-hosted, no tiers. Per-kit LICENSE-AND-USAGE.txt has the
details and the no-questions refund policy.

Generated by Shopifont — shopifont.app
`;
}

function main(): void {
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });

  let fileCount = 0;
  const wc = (p: string, b: string) => {
    w(p, b);
    fileCount++;
  };

  wc("README.txt", topReadme());

  for (const kit of KITS) {
    const root = kit.slug;
    wc(`${root}/README.txt`, kitReadme(kit));
    wc(`${root}/SPECIMEN.html`, specimenHtml(kit));
    wc(`${root}/fonts/DOWNLOAD.txt`, downloadTxt(kit));
    wc(`${root}/LICENSE-AND-USAGE.txt`, licenseTxt(kit));
    wc(`${root}/UNINSTALL.txt`, uninstallTxt(kit));

    const fontFace = fontFaceFor(kit);
    const cssVars = cssVarsFor(kit);

    for (const theme of THEMES) {
      const dir = `${root}/install/${theme.slug}`;
      wc(`${dir}/font-face.css`, fontFace + "\n");
      wc(`${dir}/css-variables.css`, cssVars + "\n");
      wc(
        `${dir}/INSTALL.txt`,
        installTxt(
          kit,
          theme.name,
          theme.injectionPoint,
          theme.notableSelector,
        ),
      );
    }
  }

  // eslint-disable-next-line no-console
  console.log(
    `[build-kits] wrote ${fileCount} files for ${KITS.length} kits × ${THEMES.length} themes → ${OUT}`,
  );
}

main();
