import {
  FORMAT_MIME_TYPE,
  sortFormats,
  type FontFamily,
  type GeneratorInput,
} from "./types";
import { slugify } from "./slugify";

/**
 * Build the optional `<link rel="preload">` snippet for `theme.liquid`'s
 * `<head>`. Emitted only when `input.preloadHints` is true.
 *
 * Preloads ONLY the first format (WOFF2 by default) of the first face
 * of every family. Preloading additional faces wastes bandwidth — only
 * the typography rendered above the fold benefits from preload, and
 * that's almost always the regular weight of each family.
 *
 * The `crossorigin` attribute is required for font preloads (browsers
 * refuse to use a preloaded font without it). `type` matches the actual
 * MIME so the browser doesn't re-fetch the file under the right
 * content-type.
 *
 * Liquid: file path resolves via `{{ '<filename>' | asset_url }}` to
 * match the @font-face block's `src:` declarations.
 */
export function buildPreloadSnippet(input: GeneratorInput): string {
  if (!input.preloadHints) return "";

  const families = input.secondary
    ? [input.primary, input.secondary]
    : [input.primary];

  const links: string[] = [];
  for (const family of families) {
    const line = renderPreloadFor(family);
    if (line) links.push(line);
  }
  if (links.length === 0) return "";

  // Top-line comment for the merchant — explains where to paste and
  // why this exists. Liquid comments are `{% comment %} ... {% endcomment %}`
  // so they don't render in the browser.
  return [
    "{% comment %}",
    "  Font preload hints generated by Shopifont.",
    "  Paste this block inside <head> in layout/theme.liquid, ideally just",
    "  before the stylesheet <link>. Preloads the WOFF2 above the fold so",
    "  the LCP element renders in the brand face on first paint.",
    "{% endcomment %}",
    ...links,
  ].join("\n");
}

function renderPreloadFor(family: FontFamily): string | null {
  if (!family.name.trim()) return null;
  const firstFace = family.faces[0];
  if (!firstFace) return null;

  const ordered = sortFormats(firstFace.formats);
  const preloadFormat = ordered[0];
  if (!preloadFormat) return null;

  const stem = resolvePreloadFilename(family, firstFace);
  if (!stem) return null;

  const mime = FORMAT_MIME_TYPE[preloadFormat];
  return (
    `<link rel="preload" href="{{ '${stem}.${preloadFormat}' | asset_url }}" ` +
    `as="font" type="${mime}" crossorigin>`
  );
}

function resolvePreloadFilename(
  family: FontFamily,
  face: { filenameOverride?: string; weight: number; style: string },
): string | null {
  if (face.filenameOverride?.trim()) return face.filenameOverride.trim();

  const baseName = family.fileBaseName?.trim() || slugify(family.name);
  if (!baseName) return null;

  if (family.faces.length === 1 && !family.isVariable) return baseName;

  if (family.isVariable) {
    return face.style === "italic"
      ? `${baseName}-variable-italic`
      : `${baseName}-variable`;
  }

  const italicSuffix = face.style === "italic" ? "-italic" : "";
  return `${baseName}-${face.weight}${italicSuffix}`;
}
